/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CredibilityRouteImport } from './routes/credibility'
import { Route as DimisiTechnologiesRouteImport } from './routes/dimisi-technologies'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexnowKeyDottxtRouteImport } from './routes/indexnow-key[.]txt'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeoAuditRouteImport } from './routes/seo-audit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as OrganizationsSlugRouteImport } from './routes/organizations.$slug'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as TechnologyIndexRouteImport } from './routes/technology.index'
import { Route as TechnologySlugRouteImport } from './routes/technology.$slug'
import { Route as ApiPublicIndexnowRouteImport } from './routes/api/public/indexnow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CredibilityRoute = CredibilityRouteImport.update({
  id: '/credibility',
  path: '/credibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DimisiTechnologiesRoute = DimisiTechnologiesRouteImport.update({
  id: '/dimisi-technologies',
  path: '/dimisi-technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexnowKeyDottxtRoute = IndexnowKeyDottxtRouteImport.update({
  id: '/indexnow-key.txt',
  path: '/indexnow-key.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAuditRoute = SeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsSlugRoute = OrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyIndexRoute = TechnologyIndexRouteImport.update({
  id: '/technology/',
  path: '/technology/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologySlugRoute = TechnologySlugRouteImport.update({
  id: '/technology/$slug',
  path: '/technology/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIndexnowRoute = ApiPublicIndexnowRouteImport.update({
  id: '/api/public/indexnow',
  path: '/api/public/indexnow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credibility': typeof CredibilityRoute
  '/dimisi-technologies': typeof DimisiTechnologiesRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/search': typeof SearchRoute
  '/seo-audit': typeof SeoAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/technology/$slug': typeof TechnologySlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/technology/': typeof TechnologyIndexRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credibility': typeof CredibilityRoute
  '/dimisi-technologies': typeof DimisiTechnologiesRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/search': typeof SearchRoute
  '/seo-audit': typeof SeoAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/technology/$slug': typeof TechnologySlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/technology': typeof TechnologyIndexRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credibility': typeof CredibilityRoute
  '/dimisi-technologies': typeof DimisiTechnologiesRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/search': typeof SearchRoute
  '/seo-audit': typeof SeoAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/technology/$slug': typeof TechnologySlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/technology/': typeof TechnologyIndexRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/credibility'
    | '/dimisi-technologies'
    | '/editorial-policy'
    | '/events'
    | '/explore'
    | '/indexnow-key.txt'
    | '/methodology'
    | '/privacy'
    | '/publications'
    | '/search'
    | '/seo-audit'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/timeline'
    | '/articles/$slug'
    | '/organizations/$slug'
    | '/people/$slug'
    | '/projects/$slug'
    | '/technology/$slug'
    | '/articles/'
    | '/organizations/'
    | '/people/'
    | '/projects/'
    | '/technology/'
    | '/api/public/indexnow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/credibility'
    | '/dimisi-technologies'
    | '/editorial-policy'
    | '/events'
    | '/explore'
    | '/indexnow-key.txt'
    | '/methodology'
    | '/privacy'
    | '/publications'
    | '/search'
    | '/seo-audit'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/timeline'
    | '/articles/$slug'
    | '/organizations/$slug'
    | '/people/$slug'
    | '/projects/$slug'
    | '/technology/$slug'
    | '/articles'
    | '/organizations'
    | '/people'
    | '/projects'
    | '/technology'
    | '/api/public/indexnow'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/credibility'
    | '/dimisi-technologies'
    | '/editorial-policy'
    | '/events'
    | '/explore'
    | '/indexnow-key.txt'
    | '/methodology'
    | '/privacy'
    | '/publications'
    | '/search'
    | '/seo-audit'
    | '/sitemap.xml'
    | '/sources'
    | '/terms'
    | '/timeline'
    | '/articles/$slug'
    | '/organizations/$slug'
    | '/people/$slug'
    | '/projects/$slug'
    | '/technology/$slug'
    | '/articles/'
    | '/organizations/'
    | '/people/'
    | '/projects/'
    | '/technology/'
    | '/api/public/indexnow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CredibilityRoute: typeof CredibilityRoute
  DimisiTechnologiesRoute: typeof DimisiTechnologiesRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  IndexnowKeyDottxtRoute: typeof IndexnowKeyDottxtRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicationsRoute: typeof PublicationsRoute
  SearchRoute: typeof SearchRoute
  SeoAuditRoute: typeof SeoAuditRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  OrganizationsSlugRoute: typeof OrganizationsSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  TechnologySlugRoute: typeof TechnologySlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TechnologyIndexRoute: typeof TechnologyIndexRoute
  ApiPublicIndexnowRoute: typeof ApiPublicIndexnowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credibility': {
      id: '/credibility'
      path: '/credibility'
      fullPath: '/credibility'
      preLoaderRoute: typeof CredibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimisi-technologies': {
      id: '/dimisi-technologies'
      path: '/dimisi-technologies'
      fullPath: '/dimisi-technologies'
      preLoaderRoute: typeof DimisiTechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexnow-key.txt': {
      id: '/indexnow-key.txt'
      path: '/indexnow-key.txt'
      fullPath: '/indexnow-key.txt'
      preLoaderRoute: typeof IndexnowKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-audit': {
      id: '/seo-audit'
      path: '/seo-audit'
      fullPath: '/seo-audit'
      preLoaderRoute: typeof SeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug': {
      id: '/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof OrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/': {
      id: '/technology/'
      path: '/technology'
      fullPath: '/technology/'
      preLoaderRoute: typeof TechnologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/$slug': {
      id: '/technology/$slug'
      path: '/technology/$slug'
      fullPath: '/technology/$slug'
      preLoaderRoute: typeof TechnologySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/indexnow': {
      id: '/api/public/indexnow'
      path: '/api/public/indexnow'
      fullPath: '/api/public/indexnow'
      preLoaderRoute: typeof ApiPublicIndexnowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CredibilityRoute: CredibilityRoute,
  DimisiTechnologiesRoute: DimisiTechnologiesRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  IndexnowKeyDottxtRoute: IndexnowKeyDottxtRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  PublicationsRoute: PublicationsRoute,
  SearchRoute: SearchRoute,
  SeoAuditRoute: SeoAuditRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  OrganizationsSlugRoute: OrganizationsSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  TechnologySlugRoute: TechnologySlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TechnologyIndexRoute: TechnologyIndexRoute,
  ApiPublicIndexnowRoute: ApiPublicIndexnowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
